### ISSUE TITLE
Upgrading the view of the page

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#1]
### Anyone can work in it.

- **Just give a screen shot of your work
- Do pull request
- I will merge if accepted**

_Thank You_

**Comment by NajeebaNasir** [comment]
Hi @Soumyajit2825 , I am Najeeba(Front End Developer) and i would like to work on this issue.

**Comment by Soumyajit2825** [comment]
Yeah sure go with it.. Share a screen after your work and then do a PR

**Comment by 21omkarsase** [comment]
> ### Anyone can work in it.
> * **Just give a screen shot of your work
> * Do pull request
> * I will merge if accepted**
> 
> _Thank You_

Hey @Soumyajit2825 , I have upgraded view for the page and opened a pull request.
Also I have attached screenshots of my work along with PR.
Please review it.
