### ISSUE TITLE
VIDEO section bug fix*

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#10]
- [x] In Video section 1 video is not playing . Delete that particular video
- [x] Add some more videos in the video section
**Put a screen-shot of your work and then do PR**

**Comment by hemantwasthere** [comment]
@Soumyajit2825 can i work on this issue

**Comment by Soumyajit2825** [comment]
Yes

**Comment by Soumyajit2825** [comment]
@Anant2961 u can work on this also

**Comment by Anant2961** [comment]
Sure i will

**Comment by Anant2961** [comment]
Assign this bug to me as i have Resolved it 
![Screenshot from 2022-10-08 14-12-49](https://user-images.githubusercontent.com/76880810/194698619-fac7819e-ee1d-4222-8431-049c3e34b82a.png)

**Comment by Soumyajit2825** [comment]
Yeah do PR now

**Comment by Anant2961** [comment]
done it
