### ISSUE TITLE
Hamburger Menu Text Visibility Issue on Mobile

### ISSUE THREAD

**Issue by Soumojitshome2023** [Soumyajit2825/MESSI_MANIA#106]
## Problem:
In the mobile view of the website, the text within the hamburger menu is not clearly visible, impacting the user experience and accessibility.

## Expected Behavior:
The text within the hamburger menu should have sufficient contrast and visibility to ensure users can easily read and understand the menu options.

## Steps to Reproduce:

1. Access the website on a mobile device or use a responsive design tool.
2. Open the hamburger menu.

## Current Behavior:
The text within the hamburger menu is not clearly visible, possibly due to low contrast or other styling issues.

## Screenshot 
![image](https://github.com/Soumyajit2825/MESSI_MANIA/assets/121761154/5ed8ff51-a8b2-4517-85b7-f8a9fa83838c)

**Comment by Soumojitshome2023** [comment]
Please assign me this issue I want to work on it.

**Comment by lord-cyclone100** [comment]
@5h0ov I want to work on this issue

**Comment by 5h0ov** [comment]
> Please assign me this issue I want to work on it.

@Soumojitshome2023  any update?

**Comment by 5h0ov** [comment]
@Soumojitshome2023  it has been 4 days now i am assigning it to @lord-cyclone100  instead now!

**Comment by 5h0ov** [comment]
@lord-cyclone100 you can go for it!
