### ISSUE TITLE
Adding image zoom in gallery feature

### ISSUE THREAD

**Issue by lord-cyclone100** [Soumyajit2825/MESSI_MANIA#110]
When any one of the images from the photo section is clicked, the picture gets zoomed, the background turns dark and only that zoomed picture and a small cross mark is displayed. On clicking the cross mark everything turns back to normal.
Something similar to this  and it would be responsive too
![1-media-popup](https://github.com/Soumyajit2825/MESSI_MANIA/assets/121711381/ef041490-e4bd-4b87-926b-b447ad935a1d)
pls assign me this task @Soumyajit2825 @5h0ov

**Comment by 5h0ov** [comment]
@lord-cyclone100  go for it!

**Comment by lord-cyclone100** [comment]
@5h0ov 
The 3rd photo looks quite distorted as originally it is a potrait orientation photo but it has been forced into a landscape one in the website....so can i change that photo to some other one?

**Comment by 5h0ov** [comment]
> @5h0ov The 3rd photo looks quite distorted as originally it is a potrait orientation photo but it has been forced into a landscape one in the website....so can i change that photo to some other one?

hm try find a similar photo then
