### ISSUE TITLE
Adding animation on scroll 

### ISSUE THREAD

**Issue by 123shreyanvi** [Soumyajit2825/MESSI_MANIA#118]
**Describe the feature you are requesting**

Adding scroll animation will make it more attractive to the user for example as you scroll up the page the images and section zoom in/out swipe flip etc..

**Additional context(if any)**

***Are you contributing under any open-source program ?***

Apertre

**Comment by Soumyajit2825** [comment]
What kind of animations you wanna add? @123shreyanvi

**Comment by 123shreyanvi** [comment]
Zoom in/out flip in/out

**Comment by Soumyajit2825** [comment]
@123shreyanvi go for it!

**Comment by 123shreyanvi** [comment]
> @123shreyanvi go for it!

done
