### ISSUE TITLE
Addition of Timeline

### ISSUE THREAD

**Issue by Souvik34** [Soumyajit2825/MESSI_MANIA#121]
**Describe the feature you are requesting**
If there is a timeline then it will be more easy to read and go through the various timelines and events of Leo Messi

**Additional context(if any)**

***Are you contributing under any open-source program ?***
Apertre

**Comment by Souvik34** [comment]
If you approve the issue then assign me

**Comment by Soumyajit2825** [comment]
@Souvik34 any update?

**Comment by lord-cyclone100** [comment]
@Soumyajit2825 @5h0ov pls assign me this task

**Comment by Soumyajit2825** [comment]
@lord-cyclone100 Tomorrow is the deadline for Apertre'24
Do it by then
