### ISSUE TITLE
Scroll up button too large

### ISSUE THREAD

**Issue by Souvik34** [Soumyajit2825/MESSI_MANIA#122]
**Describe the bug**

Scroll up button is too big. 
And its not looking appropriate here

**Expected behavior**

I shall resize it and shall add a football animation

**Screenshots**

<img width="913" alt="image" src="https://github.com/Soumyajit2825/MESSI_MANIA/assets/98397984/ef48a05c-7fd9-47a4-bed6-0c2da7c1c4a9">

**Additional context(if any)**

***Are you contributing under any open-source program ?***

Apertre

**Comment by Soumyajit2825** [comment]
@Souvik34 any update????

**Comment by Souvik34** [comment]
Yeah I opened the PR
