### ISSUE TITLE
Creating a section for Contact Purposes just before the Footer

### ISSUE THREAD

**Issue by Sapta-Dev27** [Soumyajit2825/MESSI_MANIA#128]
I would like to create a new contact section for the website just before the footer so that if anyone tries to contact the person  who made the website , they can contact it . It would contact a email , number , name , ask any question placeholders and a submit button . I would add proper CSS to it and make it completely responsive for all devices .Kindly assign me this task.

**Comment by Soumyajit2825** [comment]
not needed
thanks
