### ISSUE TITLE
Bug *fix

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#13]
![MESSI_MANIA](https://user-images.githubusercontent.com/100519291/194691710-6d870ed1-d152-45b6-8ba0-868fed07e98d.png)

- Fix this gap issue between the "VIDEO" "PHOTO" "MORE" sections
- Make the sections some more attractive

**Comment by shubhamrawat090** [comment]
hey @Soumyajit2825 can you assign this to me?

**Comment by Soumyajit2825** [comment]
@shubhamrawat090 yeah sure. Make sure that u're working on the mentioned issues. Just put a ss after your work

**Comment by pravincoder** [comment]
hey there i have remove the spacing below is the ss

**Comment by pravincoder** [comment]
hey there i have remove the spacing below is the ss @Soumyajit2825 
![section space ](https://user-images.githubusercontent.com/59168712/194694902-a5a3c12e-1b60-4408-9f43-833f81db044b.jpg)

**Comment by pravincoder** [comment]
So can you assign this to me @Soumyajit2825

**Comment by Soumyajit2825** [comment]
Can u do something with the above blank spaces???it's looking odd right!!

**Comment by Anant2961** [comment]
Hey @Soumyajit2825 , Can you Assign me to this task as i can fix this issue and will do PR to your repo in some time

**Comment by pravincoder** [comment]
yep! on it @Soumyajit2825 


> Can u do something with the above blank spaces???it's looking odd right!!

yep! on it @Soumyajit2825

**Comment by Soumyajit2825** [comment]
@pravincoder ok go ahead

**Comment by pravincoder** [comment]
> Can u do something with the above blank spaces???it's looking odd right!!

Yep ! on it . @Soumyajit2825

**Comment by Soumyajit2825** [comment]
@Anant2961 do your job then put a ss. If i find it helpful I will assign u and merge your pr

**Comment by Anant2961** [comment]
![Screenshot from 2022-10-08 13-13-53](https://user-images.githubusercontent.com/76880810/194696449-77ed9afc-8897-4dd1-9661-858577882ee5.png)
check this png @Soumyajit2825 and you can merge my PR if you find this helpful
