### ISSUE TITLE
Swapped photos

### ISSUE THREAD

**Issue by lord-cyclone100** [Soumyajit2825/MESSI_MANIA#144]
**Describe the bug**

These photos are swapped

**Expected behavior**

**Screenshots**
![20240119_190817.jpg]
![WhatsApp Image 2024-01-19 at 19 12 01_b4587f0a](https://github.com/Soumyajit2825/MESSI_MANIA/assets/121711381/3e47dc26-3c4b-417b-b803-184a52e725d1)

**Additional context(if any)**
Pls assign me this job so that i can correct this @5h0ov @Soumyajit2825 

***Are you contributing under any open-source program ?***

Apertre 24

**Comment by 5h0ov** [comment]
@lord-cyclone100  ok go for it!
