### ISSUE TITLE
Adding Horizontal scrollbar in Time line section in desktop mode only 

### ISSUE THREAD

**Issue by rko0211** [Soumyajit2825/MESSI_MANIA#150]
**Describe the feature you are requesting**

At present Timeline section contain 2 button to control their flow which take more time to move the cards, but if we add horizontal scroll bar instead of buttons then it would be good for user experience.

![Screenshot from 2024-01-20 04-39-26](https://github.com/Soumyajit2825/MESSI_MANIA/assets/97402824/534cd133-0167-4502-8dd0-01d4e272b0de)

**Additional context(if any)**
Kindly assign me this task.
***Are you contributing under any open-source program ?***
apertre24

**Comment by Soumyajit2825** [comment]
@rko0211 make PR before 12 AM tonight
