### ISSUE TITLE
theme toggle

### ISSUE THREAD

**Issue by chimoski** [Soumyajit2825/MESSI_MANIA#18]
Not an issue per say, but can  I add a theme toggle to the page? I would like to take that up as well

**Comment by Soumyajit2825** [comment]
yeh. Do a slider button that can toggle the theme between light and dark
and make it happen on the right side of the nav bar

**Comment by chimoski** [comment]
Alright, Assign that to me

**Comment by Soumyajit2825** [comment]
Yeah. I will do. You can start your work on it
