### ISSUE TITLE
Adding more information in the section "more"

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#2]
- Add some more informations about Lionel Messi in the "more" section
- You can add some more styles as well as videos and photos of MESSI

**Comment by Soumyajit2825** [comment]
@yuvi2565 go ahead. Add a screen shot after your work and then do a PR

**Comment by yuvi2565** [comment]
@Soumyajit2825 This is information that I have added about Messi in the more section:
![Screenshot (377)](https://user-images.githubusercontent.com/108284221/194311502-d447e208-2636-444a-a091-d12b06d3b127.png)
