### ISSUE TITLE
'Add Top-Scroll-Button'

### ISSUE THREAD

**Issue by pravincoder** [Soumyajit2825/MESSI_MANIA#22]
@Soumyajit2825  I believe we must add a top scroll button , that can make the user reach the top in **one click**.

**Comment by Soumyajit2825** [comment]
Ok go ahead with it. Put a ss after your work

**Comment by pravincoder** [comment]
@Soumyajit2825 thank you!
 I will upload a ss in few min

**Comment by pravincoder** [comment]
Here is the ss of the page!
 
![Screenshot 2022-10-08 195958](https://user-images.githubusercontent.com/59168712/194712152-699e1a3a-b0ce-49e0-bf0c-7e434e40c7ca.jpg)

**Comment by Soumyajit2825** [comment]
**WOW**
Do PR
