### ISSUE TITLE
Background and Text

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#24]
- [x] Change the background from white
- [x] Change the text styles in the "more" section and make it more attractive
- [x] Put a screen shot of your work and then do PR

**Comment by smitioswal** [comment]
Please assign this to me

**Comment by Soumyajit2825** [comment]
Ok follow the instructions and do it

**Comment by smitioswal** [comment]
Where should I put the ss of my work?

**Comment by Soumyajit2825** [comment]
take a ss and drag the file here below in the comment section

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/194713664-64cc1843-90f7-4dab-85df-26dcd69e35be.png)

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/194713702-29532335-cc01-4e31-80ac-518034894f43.png)

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/194713729-60e65d22-d030-4930-8cab-d82098abcc09.png)

**Comment by Soumyajit2825** [comment]
Nice work. Do Pull request now

**Comment by smitioswal** [comment]
Thank you, on it! @Soumyajit2825
