### ISSUE TITLE
*BUG fix

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#30]
- [x] The toggle dark-theme button is not working. Fix it
- [x] "Go to the top" button is having a background colour and it's doing a issue . Fix it
![Screenshot 2022-10-08 225603](https://user-images.githubusercontent.com/100519291/194719975-fcda4851-c8a5-4a09-9cad-65fb793c5378.png)
**Fix it**
**Put the seperated screen-shots of the 2 issues**
Then do PR
I will merge it

**Comment by Potato-29** [comment]
Hi, @Soumyajit2825 would also like to work on this aswell

**Comment by roldanbp** [comment]
Hey, @Soumyajit2825 I hope you are doing well. 

i'd like to help with this one too.

Regards.

**Comment by Soumyajit2825** [comment]
**Both of you @Potato-29 and @roldanbp can solve the mentioned issues
Just put screen shots of your works
I will merge the best one
Thank You 👍🏻**

**Comment by Potato-29** [comment]
Hi @Soumyajit2825 , fixed both the issues
1. White bg on scroll to top btn
2. dark theme toggle working now

https://user-images.githubusercontent.com/53327808/194722745-400f9363-dd89-4a5a-94ee-3c0f2cbc27db.mp4

**Comment by Soumyajit2825** [comment]
Nice ya!
Do PR now
