### ISSUE TITLE
Change the bg colour

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#31]
- [x] Change the background-colour of the "GOD OF FOOTBALL" section
- [x] Change the text-font of the "GOD OF FOOTBALL" section
![Screenshot 2022-10-08 225906](https://user-images.githubusercontent.com/100519291/194720093-6a4554f5-522c-4af5-a40f-0688a706d03b.png)

**Make sure that no other changes are made by you**

**Comment by Potato-29** [comment]
Hi @Soumyajit2825 , I'd like to fix this for you really quick :D

**Comment by roldanbp** [comment]
Hey, @Soumyajit2825 I hope you are doing well. 

Can i help you with this one?

Regards

**Comment by Soumyajit2825** [comment]
> Hi @Soumyajit2825 , I'd like to fix this for you really quick :D

Ok go ahead 
put a ss after your work then i will asiign u and merge your pr

**Comment by Soumyajit2825** [comment]
> Ok go ahead
> put a ss after your work then i will asiign u and merge your pr

Ok go ahead
put a ss after your work then i will asiign u and merge your pr

**Comment by Potato-29** [comment]
Hi @Soumyajit2825 does this look appealing to you? I matched the bg with his jersey colors

![image](https://user-images.githubusercontent.com/53327808/194721697-e6d34d04-2c5f-4186-b26d-436e7dfedfa8.png)

**Comment by Soumyajit2825** [comment]
I'M thinking about something else
Look the pink colour is not matching with "MESSI"
right?
So i want to see a relatable background color or image in that section
Go through it if you can

**Comment by Potato-29** [comment]
alright leave it to me

**Comment by Soumyajit2825** [comment]
ok go ahead

**Comment by Potato-29** [comment]
Hi @Soumyajit2825 does this look good and feel free to drop in suggestions cause I don't know much about football so I was confused as to what would be a good background 

![image](https://user-images.githubusercontent.com/53327808/194722378-13cec6fc-9271-46f8-90cf-b4b229d29103.png)

**Comment by Soumyajit2825** [comment]
Yeah it's looking good now. Do PR. I will merge

**Comment by Potato-29** [comment]
made a single PR for both of the issues, you can review them

**Comment by Soumyajit2825** [comment]
Yes I have merged them. Give a star to our repo if you loved to work with us
Thank You
