### ISSUE TITLE
Add the names of all contributors

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#35]
- [ ] Add a Section in the readme.md file where all the name of the contributors and their images will shown
- [x] Add a Demo screen-shot of the index.html website in the top of the README.md file

**Put separated screen-shots of the above 2 issues and do PR**
**Make sure that you're not doing any changes in the code section**
Thank You 👍🏻

**Comment by smitioswal** [comment]
Please assign this to me

**Comment by Pavan-Kamthane** [comment]
@Soumyajit2825  Assign Me

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/194741647-3907ee27-20c5-4936-84b4-11187d52f3cf.png)

**Comment by Soumyajit2825** [comment]
Yeaah almost done. But why the github links are there.. Can u make it hidden?

**Comment by smitioswal** [comment]
![image](https://user-images.githubusercontent.com/92663204/194742359-66f25066-3056-4bf7-804a-913a8dbe36de.png)

**Comment by Soumyajit2825** [comment]
nice change the spelling of the "Contributors"
You have done a typo mistake
DO that and do PR i will merge it sure
