### ISSUE TITLE
Update the links

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#41]
- [x] In the section "GOD OF FOOTBALL" the buttons wikipedia, instagram and facebook are currently having no hover effects. Add some styling button to them and add hover effect
- [x] Add icons of wikipedia , instagram and facebook besides them
![Screenshot 2022-10-09 161048](https://user-images.githubusercontent.com/100519291/194752282-1c2954f7-092c-4f5e-84c4-3a262253f993.jpg)
Go through the picture for better understanding
**Give a screen-shot of your work and then do your Pull Request**

**Comment by 21omkarsase** [comment]
Hey @Soumyajit2825, can you assign this to me.
I can do this.

**Comment by Soumyajit2825** [comment]
@21omkarsase go ahead
At last put a screen-shot and then i WIll assign it to u under hacktoberfest label

**Comment by 21omkarsase** [comment]
Hii @Soumyajit2825, I have made some changes and updated the code.
Please review it.
Should I make pull request ?

![1](https://user-images.githubusercontent.com/77478864/194758650-c0241511-2881-47b9-86a3-c21040583980.png)
![2](https://user-images.githubusercontent.com/77478864/194758652-612960cf-4253-4814-8c77-a88445a67a84.png)
![3](https://user-images.githubusercontent.com/77478864/194758654-3e870322-b638-4a0a-b633-c93e4a6d0af5.png)

**Comment by Soumyajit2825** [comment]
Yeah
Awesome!!!
Do PR
