### ISSUE TITLE
Add Hover-play video

### ISSUE THREAD

**Issue by pravincoder** [Soumyajit2825/MESSI_MANIA#42]
@Soumyajit2825  Make the video run when we place the cursor over the video player !

**Comment by Soumyajit2825** [comment]
@pravincoder Yeah with that can you add zoom-in on hover on the images in the "images" section??

**Comment by pravincoder** [comment]
> @pravincoder Yeah with that can you add zoom-in on hover on the images in the "images" section??
yes I will try it too! @Soumyajit2825

**Comment by pravincoder** [comment]
https://user-images.githubusercontent.com/59168712/194759408-e706e269-c60d-4342-9863-84d11ee53d16.mp4

@Soumyajit2825

**Comment by pravincoder** [comment]
@Soumyajit2825  SO YOU WANT ME TO ADD A ZOOM-IN ON HOVER OF CURSOR

**Comment by Soumyajit2825** [comment]
@pravincoder yeah do that also
Then i will merge your PR fixing both the issues

**Comment by Soumyajit2825** [comment]
@pravincoder any update of your work on the issue>>>>

**Comment by pravincoder** [comment]
WORKING ON IT @Soumyajit2825

**Comment by Soumyajit2825** [comment]
ok

**Comment by pravincoder** [comment]
@Soumyajit2825 not getting a proper way to enlarge the player and the img on hover of mouse
🤦‍♂️😢

**Comment by Soumyajit2825** [comment]
Ok let it go
just to PR with the hover:play video
