### ISSUE TITLE
Standardize Fonts across the Website

### ISSUE THREAD

**Issue by stringer1000** [Soumyajit2825/MESSI_MANIA#45]
Name a font family you would like to use and I would standardize all the font styles with font color and padding/margin(if necessary) in the website. 
And also add image of Messi with 7x Ballon D'Or instead of the current 6. 😄 
If approved I would like to work on this issue.

**Comment by Soumyajit2825** [comment]
Go ahead change the fonts style according to you
Give a screen-shot after your work
I will give you review
