### ISSUE TITLE
Improvements in styles and some bug fixes 

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#47]
![Screenshot 2022-10-10 174405](https://user-images.githubusercontent.com/100519291/194864987-652357d0-8e75-4586-a43b-bc05f67d1261.jpg)

- [ ] Update the style of the buttons of the "nav" area **Don't break the screen responsiveness**
- [ ] You can change the nav-button icons also to look it better
- [ ] If anyone can add a "KEBAB MENU" for the navbar for small screens like phone or tab views it will be awesome

KEBAB MENU example code link :- [Here](https://codepen.io/mildrenben/pen/MwezWG)

**Comment by hemantwasthere** [comment]
@Soumyajit2825 Can i work on this issue

**Comment by Soumyajit2825** [comment]
@hemantwasthere Yeah make sure that u're only working on the mentioned things nothing else
