### ISSUE TITLE
Navbar styling

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#52]
![Screenshot 2022-10-11 112026](https://user-images.githubusercontent.com/100519291/195007157-63d074e9-3d6c-49e9-9db5-1d03ba1d46f8.jpg)
I need some more stylish nav-bar

- You can change the nav-bar background color
- You can change the nav-bar stylings using bootstrap
**Put a screen-shot or a small video of your work**

**Comment by TriinK** [comment]
Assign me this please

**Comment by Soumyajit2825** [comment]
Do changes
If i find your work helpful i will assign you and merge your PR

**Comment by bhavy2202** [comment]
If this is still open, please assign me

**Comment by Soumyajit2825** [comment]
Done
Put a screen shot of your work after you have done

**Comment by Shreya111111** [comment]
@Soumyajit2825 PLz assign this issue to me. I will do in 1-2 days

**Comment by Soumyajit2825** [comment]
ok

**Comment by bhavy2202** [comment]
Hey, is this still open? Can I work on this?

**Comment by Soumyajit2825** [comment]
@bhavy2202 yeah u can. Go ahead

**Comment by Viren0602** [comment]
Hello sir , please assign this issue to me?

**Comment by ShikhaDhiman1** [comment]
I want to contribute to this issue. Kindly assign the issue to me.

**Comment by Soumyajit2825** [comment]
ok go ahead

**Comment by ShikhaDhiman1** [comment]
![Screenshot (130)](https://user-images.githubusercontent.com/103432012/197996961-a818b2d9-20e8-4f23-a8c0-b0e41847e33c.png)

**Comment by ShikhaDhiman1** [comment]
![Screenshot (130)](https://user-images.githubusercontent.com/103432012/197997561-a848fa60-e345-49bc-af51-7eaabfb38fb4.png)

**Comment by ShikhaDhiman1** [comment]
Please check if this is OK.

**Comment by ShikhaDhiman1** [comment]
I haven't used Bootstrap.
If Bootstrap is needed I will change the code again.

**Comment by Soumyajit2825** [comment]
> I haven't used Bootstrap. If Bootstrap is needed I will change the code again.

It's awesome man
