### ISSUE TITLE
Add a Java Script file for this web page

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#6]
### How to contribute?
**See the README.md file**
ADD a screen-shot of your work and do PR then

**Comment by chimoski** [comment]
I want to work on this , Please assign it to me

**Comment by tokyo3001** [comment]
@Soumyajit2825 can you assign me this issue?

**Comment by Soumyajit2825** [comment]
Yeah go ahead. Put a screen shot of your work

**Comment by Soumyajit2825** [comment]
@tokyo3001 u can work with other issues that i've mentioned. Thank u
