### ISSUE TITLE
Improve the "Facts" section style and designs

### ISSUE THREAD

**Issue by Soumyajit2825** [Soumyajit2825/MESSI_MANIA#63]
![Screenshot 2022-10-16 181224](https://user-images.githubusercontent.com/100519291/196035998-4f8a57df-ab1f-4a39-a226-94e725453fa8.jpg)
**Put a screen-shot of your changes after your work**

**Comment by swapn652** [comment]
Can I work on this?

**Comment by amarprajapati571** [comment]
hii i am full stack engineer. i can work on this
