### ISSUE TITLE
Need to work on responsiveness of site

### ISSUE THREAD

**Issue by swapn652** [Soumyajit2825/MESSI_MANIA#65]
![image](https://user-images.githubusercontent.com/70851202/197384446-7f2e1a8b-f6cc-40c7-908f-77bc911f9e00.png)
![image](https://user-images.githubusercontent.com/70851202/197384464-c0bf7769-86cb-43d7-8d38-86cfb9158dd9.png)
![image](https://user-images.githubusercontent.com/70851202/197384477-4feb1594-8c9f-4148-8429-74a3a17961ac.png)
![image](https://user-images.githubusercontent.com/70851202/197384489-5c3b973b-ac94-450a-bf10-b34577f8434e.png)
![image](https://user-images.githubusercontent.com/70851202/197384499-c1793b5c-edee-4c47-b875-5d7c10ba100e.png)

### Assign me, I will work on it.

**Comment by Soumyajit2825** [comment]
Give a screen shot after your work
