### ISSUE TITLE
Fix image size and width of the video in Responsive Web Design

### ISSUE THREAD

**Issue by Geeks-Arpan** [Soumyajit2825/MESSI_MANIA#72]
![Messi](https://github.com/Soumyajit2825/MESSI_MANIA/assets/99377659/1958641b-bd75-47e6-ad13-9fd2c62b12e1)
![Screenshot 2023-12-31 184537](https://github.com/Soumyajit2825/MESSI_MANIA/assets/99377659/b7de87fc-8b07-47cd-a8bf-4c143c1befcc)

**Comment by YooAshu** [comment]
@Soumyajit2825 pls assign me to work on this issue

**Comment by Soumyajit2825** [comment]
@YooAshu you can fix the specified issues in the video section and the other one and fix the responsiveness. You have 1 day to solve these
