### ISSUE TITLE
Feature_Request Making the navbar look cool

### ISSUE THREAD

**Issue by sayan-1210** [Soumyajit2825/MESSI_MANIA#80]
**Describe the feature you are requesting**
Currently the navbar looks  very cringy. I want to give it a cool look

**Additional context(if any)**

***Are you contributing under any open-source program ?***
Aperture

**Comment by Soumyajit2825** [comment]
@sayan-1210 go on! try to complete it within 2 days

**Comment by Soumyajit2825** [comment]
@sayan-1210 any update of the work?

**Comment by sayan-1210** [comment]
Please check it 
I have made the PR
