### ISSUE TITLE
Website is not responsive for mobile device

### ISSUE THREAD

**Issue by rko0211** [Soumyajit2825/MESSI_MANIA#84]
**Describe the bug**

The website is not user friendly for mobile user as it not completely responsive.
**Expected behavior**

Some elements of the website go out of their  actual container range
**Screenshots**
If applicable, add screenshots to help explain your problem. -->
![responsiveness](https://github.com/Soumyajit2825/MESSI_MANIA/assets/97402824/14f63a09-52a7-4baa-b554-c4cd685549aa)

**Additional context(if any)**
Kindly assign me this issue i want to work in this under **apertre24**.
***Are you contributing under any open-source program ?***

Yes, Apertre24

**Comment by Soumyajit2825** [comment]
@rko0211 any update of this work?

**Comment by rko0211** [comment]
iya i am working in this

**Comment by Soumyajit2825** [comment]
Ok no problem!
