### ISSUE TITLE
Footer is not beautiful 

### ISSUE THREAD

**Issue by rko0211** [Soumyajit2825/MESSI_MANIA#93]
**Describe the bug**

Footer is not beautiful

**Expected behavior**

**Screenshots**

![p4](https://github.com/Soumyajit2825/MESSI_MANIA/assets/97402824/62d3aaac-276c-4d8c-81c4-c8146d69474e)

**Additional context(if any)**

***Are you contributing under any open-source program ?***

apertre24

**Comment by rko0211** [comment]
Please assign me this issue.

**Comment by Soumyajit2825** [comment]
> Please assign me this issue.

done!
